### ISSUE TITLE
Typo I believe

### ISSUE THREAD

**Issue by muschellij2** [skeydan/lesion_segmentation#1]
I believe line https://github.com/skeydan/lesion_segmentation/blob/master/flexconn.R#L149 should be assignment not < (missing a -).  
Thus,  I think it should be 
```r
count1 <- count1 + pdim[1] 
```

We may also want to have a check on `pdim[1] > 0`, but that shouldn't really ever happen.

**Comment by skeydan** [comment]
right, thanks for spotting this!

Regarding sanity checks etc., that for sure makes sense, but I suggest we switch to the package for things like that?

**Comment by skeydan** [comment]
Update: Glad you spotted that! That uncovered something else, I'll add a corresponding issue in flexconn

**Comment by skeydan** [comment]
actually I think in ```get_2d_patch_from_volume``` you have it already, so nothing to do
